library(dplyr)
library(ggplot2)
library(googleVis)
source("helper.R")
library(shiny)
library(shinydashboard)
library(markdown)
library(plotly)

top10 = read.csv("~/Desktop/Project2/Top10.csv", stringsAsFactors = F)
size = read.csv("~/Desktop/Project2/Size.csv", stringsAsFactors = F)
price = read.csv("~/Desktop/Project2/Price.csv", stringsAsFactors = F)
package = read.csv("~/Desktop/Project2/Package.csv", stringsAsFactors = F)
top10$Time <- as.Date(top10$Time, "%m/%d/%y")
size$Time <- as.Date(size$Time, "%m/%d/%y")
price$Time <- as.Date(price$Time, "%m/%d/%y")
package$Time <- as.Date(package$Time, "%m/%d/%y")
# ggplot(data = top10, aes(x=Time, y=Revenue)) + geom_point(aes(color = Brand)) + geom_line(aes(color = Brand, group = Brand))
# ggplot(data = size, aes(x=Time, y=Revenue)) + geom_point(aes(color = Size_Interval)) + geom_line(aes(color = Size_Interval, group = Size_Interval))
# ggplot(data = price, aes(x=Time, y=Revenue)) + geom_point(aes(color = Price_Interval)) + geom_line(aes(color = Price_Interval, group = Price_Interval))
# ggplot(data = package, aes(x=Time, y=Revenue)) + geom_point(aes(color = Package)) + geom_line(aes(color = Package, group = Package))
# ggplot(data = size, aes(x = color)) + geom_bar(aes(fill = cut), position = "stack")

